### ISSUE TITLE
crash occurred during the use of the library 

### ISSUE THREAD

**Issue by ChriAV** [i10/ThoMoNetworking#3]

**Comment by Finndarmin** [comment]
Hey annsami,

unfortunately, I am not sure if I can help you with your issue. 
First of all, ThoMo Networking was never meant to do interprocess communication.
That is also why it is not fail-safe against run loop null pointers.
Additionally, just from this error message, there is little I can see about the actual issue.
Are you sure the process your working on is currently running?

Hope this helps at least a little.
Cheers

**Comment by annsami** [comment]
can I have your email? 
I will send you the details of the problem
